/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ias.iotviewer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketAddress;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author METIN
 */
public class IotFramev2 extends javax.swing.JFrame {

    private String serviceIP;
    private int servicePort;
    private int period;
    private Socket socket;
    private Socket interruptSerialSocket;
    private UIHelper uiHelper;
    private Timer timer;

    private final String PREF_IOTBOX_IP = "IotBoxIP";
    private final String PREF_IOTBOX_PORT = "IotBoxPort";
    private final String PREF_PERIOD = "IotBoxPeriod";

    private final int INT_SERIAL_PORT = 5556;

    final static Logger logger = Logger.getLogger("IotFramev2");
    Preferences prefs = Preferences.userNodeForPackage(com.ias.iotviewer.IotFramev2.class);

    /**
     * Creates new form IotFramev2
     */
    public IotFramev2() {
        initComponents();
        jPanel1.setVisible(false);
        PropertyConfigurator.configure("log4j.properties");
        String iotBoxIP = prefs.get(PREF_IOTBOX_IP, "127.0.0.1");
        String iotBoxPort = prefs.get(PREF_IOTBOX_PORT, "5555");
        String iotBoxPeriod = prefs.get(PREF_PERIOD, "1000");
        srvIP.setText(iotBoxIP);
        srvPort.setText(iotBoxPort);
        txtPeriod.setText(iotBoxPeriod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        srvIP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        srvPort = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPeriod = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtPin13 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPin22 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPin26 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtPin32 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPin24 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPin19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPin21 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtPin23 = new javax.swing.JTextField();
        serTxt1 = new javax.swing.JTextField();
        serTxt2 = new javax.swing.JTextField();
        btnSendToSerial1 = new javax.swing.JButton();
        btnSendToSerial2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPin7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPin12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IoT Monitor by IAS v1.02");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setText("IoTBox IP:");

        srvIP.setName("dvcIP"); // NOI18N

        jLabel5.setText("IoTBox Port:");

        srvPort.setName("dvcPort"); // NOI18N

        jLabel6.setText("Read/Write Period (m/s):");

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jLabel16.setText("#13");

        txtPin13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin13KeyReleased(evt);
            }
        });

        jLabel29.setText("#22");

        txtPin22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin22KeyReleased(evt);
            }
        });

        jLabel33.setText("#26");
        jLabel33.setToolTipText("");

        txtPin26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin26KeyReleased(evt);
            }
        });

        jLabel35.setText("#32");

        txtPin32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin32KeyReleased(evt);
            }
        });

        jLabel1.setText("OPT");

        jLabel2.setText("DOUT");

        jLabel3.setText("INT");

        jLabel31.setText("#24");

        txtPin24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin24KeyReleased(evt);
            }
        });

        jLabel22.setText("#19");

        txtPin19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin19KeyReleased(evt);
            }
        });

        jLabel27.setText("#21");

        txtPin21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin21KeyReleased(evt);
            }
        });

        jLabel30.setText("#23");

        txtPin23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin23KeyReleased(evt);
            }
        });

        serTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTxt1KeyTyped(evt);
            }
        });

        serTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTxt2KeyTyped(evt);
            }
        });

        btnSendToSerial1.setText("Send");
        btnSendToSerial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToSerial1ActionPerformed(evt);
            }
        });

        btnSendToSerial2.setText("Send");
        btnSendToSerial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToSerial2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Serial #2");

        jLabel8.setText("Serial #1");

        jLabel10.setText("#7");

        txtPin7.setEditable(false);
        txtPin7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin7KeyReleased(evt);
            }
        });

        jLabel15.setText("#12");

        txtPin12.setEditable(false);
        txtPin12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin12KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendToSerial2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(serTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendToSerial1)))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPin7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPin26, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(txtPin32, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(4, 4, 4)
                                            .addComponent(txtPin13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPin22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel30))
                                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPin19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtPin24, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPin12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtPin13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPin22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPin26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(txtPin32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addGap(41, 41, 41)))
                                .addGap(35, 35, 35))
                            .addComponent(jLabel27))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPin19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtPin24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)))))
                                .addGap(35, 35, 35))
                            .addComponent(txtPin21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPin23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(serTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSendToSerial1))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendToSerial2)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srvIP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(srvPort, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConnect))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(srvPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConnect)
                        .addComponent(jLabel6)
                        .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(srvIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPin13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin13KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin13KeyReleased

    private void txtPin22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin22KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin22KeyReleased

    private void txtPin26KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin26KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin26KeyReleased

    private void txtPin32KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin32KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin32KeyReleased

    private void txtPin24KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin24KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin24KeyReleased

    private void txtPin19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin19KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin19KeyReleased

    private void txtPin21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin21KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin21KeyReleased

    private void txtPin23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin23KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin23KeyReleased

    private void serTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTxt1KeyTyped
        if ((serTxt1.getText() + evt.getKeyChar()).length() > 16) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_serTxt1KeyTyped

    private void serTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTxt2KeyTyped
        if ((serTxt2.getText() + evt.getKeyChar()).length() > 16) {
            evt.consume();
        }          
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_serTxt2KeyTyped

    private void showErrorMsg(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if (srvIP.getText().equals("")) {
            showErrorMsg("Service IP is required.");
        } else if (srvPort.getText().equals("")) {
            showErrorMsg("Service Port is required.");
        } else if (txtPeriod.getText().equals("")) {
            showErrorMsg("Period is required.");
        }

        if (!srvIP.getText().equals("") && !srvPort.getText().equals("") && !txtPeriod.getText().equals("")) {
            int port = Integer.parseInt(srvPort.getText());
            period = Integer.parseInt(txtPeriod.getText());

            prefs.put(PREF_IOTBOX_IP, srvIP.getText());
            prefs.put(PREF_IOTBOX_PORT, srvPort.getText());
            prefs.put(PREF_PERIOD, txtPeriod.getText());

            try {
                SocketAddress sockaddr = new InetSocketAddress(srvIP.getText(), port);
                socket = new Socket();
                socket.connect(sockaddr, 15000);
                if (socket.isConnected()) {
                    serviceIP = srvIP.getText();
                    servicePort = port;

                    jPanel1.setVisible(true);

                    btnConnect.setEnabled(false);
                    btnConnect.setText("Connected");
                    srvIP.setEnabled(false);
                    srvPort.setEnabled(false);
                    txtPeriod.setEnabled(false);

                    SocketAddress sockaddr2 = new InetSocketAddress(srvIP.getText(), INT_SERIAL_PORT);
                    interruptSerialSocket = new Socket();
                    interruptSerialSocket.connect(sockaddr2, 15000);

                    uiHelper = new UIHelper(this, jPanel1, socket, interruptSerialSocket);

                    uiHelper.getPinStates2();
                    uiHelper.sendAndReceive2();

                    timer = new Timer(period, new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                            uiHelper.sendAndReceive2();
                            btnSendToSerial1.setEnabled(true);
                            btnSendToSerial2.setEnabled(true);
                        }
                    });
                    timer.start();

                }

            } catch (Exception ex) {
                ex.printStackTrace();
                showErrorMsg(ex.toString());
                logger.error("Connection error " + ex.toString());

            }

        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void txtPin7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin7KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin7KeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (uiHelper != null) {
            uiHelper.closeConnection();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnSendToSerial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToSerial1ActionPerformed
        uiHelper.writeToSerialPort(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendToSerial1ActionPerformed

    private void btnSendToSerial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToSerial2ActionPerformed
        uiHelper.writeToSerialPort(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendToSerial2ActionPerformed

    private void txtPin12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin12KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin12KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IotFramev2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSendToSerial1;
    private javax.swing.JButton btnSendToSerial2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField serTxt1;
    private javax.swing.JTextField serTxt2;
    private javax.swing.JTextField srvIP;
    private javax.swing.JTextField srvPort;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtPin12;
    private javax.swing.JTextField txtPin13;
    private javax.swing.JTextField txtPin19;
    private javax.swing.JTextField txtPin21;
    private javax.swing.JTextField txtPin22;
    private javax.swing.JTextField txtPin23;
    private javax.swing.JTextField txtPin24;
    private javax.swing.JTextField txtPin26;
    private javax.swing.JTextField txtPin32;
    private javax.swing.JTextField txtPin7;
    // End of variables declaration//GEN-END:variables
}
