/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ias.iotviewer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.SocketAddress;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import javax.swing.JTextField;

/**
 *
 * @author METIN
 */
public class IotFramev2 extends javax.swing.JFrame {

    private String serviceIP;
    private int servicePort;
    private int period;
    private Socket socket;
    private Socket interruptSerialSocket;
    private UIHelper uiHelper;
    private Timer timer;

    private final String PREF_IOTBOX_IP = "IotBoxIP";
    private final String PREF_IOTBOX_PORT = "IotBoxPort";
    private final String PREF_PERIOD = "IotBoxPeriod";

    private final int INT_SERIAL_PORT = 5556;

    final static Logger logger = Logger.getLogger("IotFramev2");
    Preferences prefs = Preferences.userNodeForPackage(com.ias.iotviewer.IotFramev2.class);

    /**
     * Creates new form IotFramev2
     */
    public IotFramev2() {
        initComponents();
        jPanel1.setVisible(false);
        PropertyConfigurator.configure("log4j.properties");
        String iotBoxIP = prefs.get(PREF_IOTBOX_IP, "127.0.0.1");
        String iotBoxPort = prefs.get(PREF_IOTBOX_PORT, "5555");
        String iotBoxPeriod = prefs.get(PREF_PERIOD, "1000");
        srvIP.setText(iotBoxIP);
        srvPort.setText(iotBoxPort);
        txtPeriod.setText(iotBoxPeriod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        srvIP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        srvPort = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPeriod = new javax.swing.JTextField();
        btnConnect = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtPin2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtPin3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPin17 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtPin18 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPin6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPin11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtPin10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtPin19 = new javax.swing.JTextField();
        serTxt1 = new javax.swing.JTextField();
        serTxt2 = new javax.swing.JTextField();
        btnSendToSerial1 = new javax.swing.JButton();
        btnSendToSerial2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPin22 = new javax.swing.JTextField();
        serWTxt1 = new javax.swing.JTextField();
        serWTxt2 = new javax.swing.JTextField();
        txtPin27 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtPin25 = new javax.swing.JTextField();
        txtPin23 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtPin21 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtPinAIN1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPinPWMIN2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtPinPWMIN1 = new javax.swing.JTextField();
        txtPinAIN2 = new javax.swing.JTextField();
        txtPinAOUT1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtPinPWMOUT = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPinAOUT2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtPinAIN1Range = new javax.swing.JTextField();
        txtPinAIN2Range = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IoT Monitor by IAS v1.06");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel4.setText("IoTBox IP:");

        srvIP.setName("dvcIP"); // NOI18N

        jLabel5.setText("IoTBox Port:");

        srvPort.setName("dvcPort"); // NOI18N

        jLabel6.setText("Pin Read Period (m/s):");

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("2");

        txtPin2.setEditable(false);
        txtPin2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin2KeyReleased(evt);
            }
        });

        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("3");

        txtPin3.setEditable(false);
        txtPin3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin3KeyReleased(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("17");
        jLabel33.setToolTipText("");

        txtPin17.setEditable(false);
        txtPin17.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin17KeyReleased(evt);
            }
        });

        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("18");

        txtPin18.setEditable(false);
        txtPin18.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin18KeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("IN");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("OUT");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("OUT ENABLE");

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("6");

        txtPin6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPin6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPin6FocusGained(evt);
            }
        });
        txtPin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPin6ActionPerformed(evt);
            }
        });
        txtPin6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin6KeyReleased(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("11");

        txtPin11.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPin11FocusGained(evt);
            }
        });
        txtPin11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin11KeyReleased(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("10");

        txtPin10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPin10FocusGained(evt);
            }
        });
        txtPin10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin10KeyReleased(evt);
            }
        });

        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("19");

        txtPin19.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPin19FocusGained(evt);
            }
        });
        txtPin19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin19KeyReleased(evt);
            }
        });

        serTxt1.setEditable(false);
        serTxt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTxt1KeyTyped(evt);
            }
        });

        serTxt2.setEditable(false);
        serTxt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serTxt2KeyTyped(evt);
            }
        });

        btnSendToSerial1.setText("Send");
        btnSendToSerial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToSerial1ActionPerformed(evt);
            }
        });

        btnSendToSerial2.setText("Send");
        btnSendToSerial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendToSerial2ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setLabelFor(serTxt2);
        jLabel7.setText("Serial #B");

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setLabelFor(serTxt1);
        jLabel8.setText("Serial #A");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("22");

        txtPin22.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin22KeyReleased(evt);
            }
        });

        serWTxt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serWTxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serWTxt1KeyTyped(evt);
            }
        });

        serWTxt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        serWTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                serWTxt2KeyTyped(evt);
            }
        });

        txtPin27.setEditable(false);
        txtPin27.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin27KeyReleased(evt);
            }
        });

        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("27");

        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("25");
        jLabel34.setToolTipText("");

        txtPin25.setEditable(false);
        txtPin25.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin25KeyReleased(evt);
            }
        });

        txtPin23.setEditable(false);
        txtPin23.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin23KeyReleased(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("23");

        txtPin21.setEditable(false);
        txtPin21.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPin21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPin21KeyReleased(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("21");

        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("AIN2");

        txtPinAIN1.setEditable(false);
        txtPinAIN1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinAIN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAIN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAIN1KeyReleased(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("AIN1");

        txtPinPWMIN2.setEditable(false);
        txtPinPWMIN2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinPWMIN2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinPWMIN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinPWMIN2KeyReleased(evt);
            }
        });

        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("PWM IN 2");

        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("PWM IN 1");
        jLabel39.setToolTipText("");

        txtPinPWMIN1.setEditable(false);
        txtPinPWMIN1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinPWMIN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinPWMIN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinPWMIN1KeyReleased(evt);
            }
        });

        txtPinAIN2.setEditable(false);
        txtPinAIN2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinAIN2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAIN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAIN2KeyReleased(evt);
            }
        });

        txtPinAOUT1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinAOUT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAOUT1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPinAOUT1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinAOUT1FocusGained(evt);
            }
        });
        txtPinAOUT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAOUT1KeyReleased(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("PWM OUT");

        txtPinPWMOUT.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinPWMOUT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinPWMOUT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinPWMOUTFocusGained(evt);
            }
        });
        txtPinPWMOUT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinPWMOUTKeyReleased(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("AOUT2");

        txtPinAOUT2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtPinAOUT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAOUT2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinAOUT2FocusGained(evt);
            }
        });
        txtPinAOUT2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAOUT2KeyReleased(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("AOUT1");

        txtPinAIN1Range.setFont(new java.awt.Font("Lucida Sans", 0, 8)); // NOI18N
        txtPinAIN1Range.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAIN1Range.setText("4-20 0-600");
        txtPinAIN1Range.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPinAIN1Range.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinAIN1RangeFocusGained(evt);
            }
        });
        txtPinAIN1Range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinAIN1RangeActionPerformed(evt);
            }
        });
        txtPinAIN1Range.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAIN1RangeKeyReleased(evt);
            }
        });

        txtPinAIN2Range.setFont(new java.awt.Font("Lucida Sans", 0, 8)); // NOI18N
        txtPinAIN2Range.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinAIN2Range.setText("4-20 0-600");
        txtPinAIN2Range.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPinAIN2Range.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinAIN2RangeFocusGained(evt);
            }
        });
        txtPinAIN2Range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinAIN2RangeActionPerformed(evt);
            }
        });
        txtPinAIN2Range.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPinAIN2RangeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel35)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel29)
                            .addComponent(jLabel33))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(serTxt2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serTxt1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPin3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel36))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPin23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin27, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin25, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin21, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel30)))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPin22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(101, 101, 101))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPin11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPin19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPin10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPin6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel37)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPinAIN1Range, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .addComponent(txtPinAIN2Range))))
                                .addGap(20, 20, 20)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPinAIN1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtPinAIN2)
                            .addComponent(txtPinPWMIN1)
                            .addComponent(txtPinPWMIN2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel28)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPinAOUT1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtPinAOUT2)
                            .addComponent(txtPinPWMOUT)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serWTxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(serWTxt2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSendToSerial1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSendToSerial2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPin21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPin23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPin25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPin27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel29))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel33))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPin18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPin19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel35))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPinAOUT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPinAOUT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPinPWMOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtPinAIN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPinAIN1Range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtPinAIN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPinAIN2Range, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel37))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPinPWMIN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))))
                        .addGap(18, 18, 18)
                        .addComponent(txtPinPWMIN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPin22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(serWTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendToSerial1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSendToSerial2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(serTxt2)
                    .addComponent(serWTxt2))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srvIP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srvPort, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConnect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(srvPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConnect)
                        .addComponent(jLabel6)
                        .addComponent(txtPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(srvIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("IoT Monitor by IAS v1.07");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showErrorMsg(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if (srvIP.getText().equals("")) {
            showErrorMsg("Service IP is required.");
        } else if (srvPort.getText().equals("")) {
            showErrorMsg("Service Port is required.");
        } else if (txtPeriod.getText().equals("")) {
            showErrorMsg("Period is required.");
        }

        if (!srvIP.getText().equals("") && !srvPort.getText().equals("") && !txtPeriod.getText().equals("")) {
            int port = Integer.parseInt(srvPort.getText());
            period = Integer.parseInt(txtPeriod.getText());

            prefs.put(PREF_IOTBOX_IP, srvIP.getText());
            prefs.put(PREF_IOTBOX_PORT, srvPort.getText());
            prefs.put(PREF_PERIOD, txtPeriod.getText());

            try {
                SocketAddress sockaddr = new InetSocketAddress(srvIP.getText(), port);
                socket = new Socket();
                socket.connect(sockaddr, 15000);
                if (socket.isConnected()) {
                    serviceIP = srvIP.getText();
                    servicePort = port;

                    jPanel1.setVisible(true);

                    btnConnect.setEnabled(false);
                    btnConnect.setText("Connected");
                    srvIP.setEnabled(false);
                    srvPort.setEnabled(false);
                    txtPeriod.setEnabled(false);

                    SocketAddress sockaddr2 = new InetSocketAddress(srvIP.getText(), INT_SERIAL_PORT);
                    interruptSerialSocket = new Socket();
                    interruptSerialSocket.connect(sockaddr2, 15000);

                    uiHelper = new UIHelper(this, jPanel1, socket, interruptSerialSocket);

                    uiHelper.getPinStates2();
                    uiHelper.checkAllPins();

                    timer = new Timer(period, new ActionListener() {

                        @Override
                        public void actionPerformed(ActionEvent e) {

                            uiHelper.sendAndReceive2();
                            btnSendToSerial1.setEnabled(true);
                            btnSendToSerial2.setEnabled(true);
                        }
                    });
                    timer.start();

                }

            } catch (Exception ex) {
                ex.printStackTrace();
                showErrorMsg(ex.toString());
                logger.error("Connection error " + ex.toString());

            }

        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (uiHelper != null) {
            uiHelper.closeConnection();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jPanel1.requestFocus();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtPin21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin21KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin21KeyReleased

    private void txtPin23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin23KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin23KeyReleased

    private void txtPin25KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin25KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin25KeyReleased

    private void txtPin27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin27KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin27KeyReleased

    private void serWTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serWTxt2KeyTyped
        if ((serWTxt2.getText() + evt.getKeyChar()).length() > 30) {
            evt.consume();
        }
        //         // TODO add your handling code here:
    }//GEN-LAST:event_serWTxt2KeyTyped

    private void serWTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serWTxt1KeyTyped
        if ((serWTxt1.getText() + evt.getKeyChar()).length() > 30) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_serWTxt1KeyTyped

    private void txtPin22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin22KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin22KeyReleased

    private void btnSendToSerial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToSerial2ActionPerformed
        uiHelper.writeToSerialPort(2);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendToSerial2ActionPerformed

    private void btnSendToSerial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendToSerial1ActionPerformed
        uiHelper.writeToSerialPort(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendToSerial1ActionPerformed

    private void serTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTxt2KeyTyped
        if ((serTxt2.getText() + evt.getKeyChar()).length() > 16) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_serTxt2KeyTyped

    private void serTxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serTxt1KeyTyped
        if ((serTxt1.getText() + evt.getKeyChar()).length() > 16) {
            evt.consume();
        }
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
            || (c == KeyEvent.VK_BACK_SPACE)
            || (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_serTxt1KeyTyped

    private void txtPin19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin19KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin19KeyReleased

    private void txtPin19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPin19FocusGained
        if (!(evt.getSource() instanceof JTextField)) return;
        JTextField txt = (JTextField)evt.getSource();
        txt.selectAll();
    }//GEN-LAST:event_txtPin19FocusGained

    private void txtPin10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin10KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin10KeyReleased

    private void txtPin10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPin10FocusGained
        if (!(evt.getSource() instanceof JTextField)) return;
        JTextField txt = (JTextField)evt.getSource();
        txt.selectAll();
    }//GEN-LAST:event_txtPin10FocusGained

    private void txtPin11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin11KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin11KeyReleased

    private void txtPin11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPin11FocusGained
        if (!(evt.getSource() instanceof JTextField)) return;
        JTextField txt = (JTextField)evt.getSource();
        txt.selectAll();
    }//GEN-LAST:event_txtPin11FocusGained

    private void txtPin6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin6KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin6KeyReleased

    private void txtPin6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPin6FocusGained

        if (!(evt.getSource() instanceof JTextField)) return;
        JTextField txt = (JTextField)evt.getSource();
        txt.selectAll();
    }//GEN-LAST:event_txtPin6FocusGained

    private void txtPin18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin18KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin18KeyReleased

    private void txtPin17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin17KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin17KeyReleased

    private void txtPin3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin3KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin3KeyReleased

    private void txtPin2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPin2KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin2KeyReleased

    private void txtPinAIN1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAIN1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN1KeyReleased

    private void txtPinPWMIN2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinPWMIN2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinPWMIN2KeyReleased

    private void txtPinPWMIN1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinPWMIN1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinPWMIN1KeyReleased

    private void txtPinAIN2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAIN2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN2KeyReleased

    private void txtPinAOUT1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinAOUT1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAOUT1FocusGained

    private void txtPinAOUT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAOUT1KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());   // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAOUT1KeyReleased

    private void txtPinPWMOUTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinPWMOUTFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinPWMOUTFocusGained

    private void txtPinPWMOUTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinPWMOUTKeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());   // TODO add your handling code here:
    }//GEN-LAST:event_txtPinPWMOUTKeyReleased

    private void txtPinAOUT2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinAOUT2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAOUT2FocusGained

    private void txtPinAOUT2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAOUT2KeyReleased
        uiHelper.sendWriteOnChange(evt.getSource());   // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAOUT2KeyReleased

    private void txtPin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPin6ActionPerformed

    private void txtPinAIN2RangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinAIN2RangeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN2RangeFocusGained

    private void txtPinAIN2RangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinAIN2RangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN2RangeActionPerformed

    private void txtPinAIN2RangeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAIN2RangeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN2RangeKeyReleased

    private void txtPinAIN1RangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinAIN1RangeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN1RangeFocusGained

    private void txtPinAIN1RangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinAIN1RangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN1RangeActionPerformed

    private void txtPinAIN1RangeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPinAIN1RangeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinAIN1RangeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IotFramev2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IotFramev2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnSendToSerial1;
    private javax.swing.JButton btnSendToSerial2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField serTxt1;
    private javax.swing.JTextField serTxt2;
    private javax.swing.JTextField serWTxt1;
    private javax.swing.JTextField serWTxt2;
    private javax.swing.JTextField srvIP;
    private javax.swing.JTextField srvPort;
    private javax.swing.JTextField txtPeriod;
    private javax.swing.JTextField txtPin10;
    private javax.swing.JTextField txtPin11;
    private javax.swing.JTextField txtPin17;
    private javax.swing.JTextField txtPin18;
    private javax.swing.JTextField txtPin19;
    private javax.swing.JTextField txtPin2;
    private javax.swing.JTextField txtPin21;
    private javax.swing.JTextField txtPin22;
    private javax.swing.JTextField txtPin23;
    private javax.swing.JTextField txtPin25;
    private javax.swing.JTextField txtPin27;
    private javax.swing.JTextField txtPin3;
    private javax.swing.JTextField txtPin6;
    private javax.swing.JTextField txtPinAIN1;
    private javax.swing.JTextField txtPinAIN1Range;
    private javax.swing.JTextField txtPinAIN2;
    private javax.swing.JTextField txtPinAIN2Range;
    private javax.swing.JTextField txtPinAOUT1;
    private javax.swing.JTextField txtPinAOUT2;
    private javax.swing.JTextField txtPinPWMIN1;
    private javax.swing.JTextField txtPinPWMIN2;
    private javax.swing.JTextField txtPinPWMOUT;
    // End of variables declaration//GEN-END:variables
}
